export default {
    default:[
        {
            title:'信用动态',
            channelIds:94,
            children:[
                {
                    title:'国内',
                    channelIds:103
                },
                {
                    title:'省内',
                    channelIds:104
                }
            ]
        },
        {
            title:'政策法规',
            channelIds:95,
            children:[
                {
                    title:'国家',
                    channelIds:105
                },
                {
                    title:'外省',
                    channelIds:106
                },
                {
                    title:'本地',
                    channelIds:121
                },
                {
                    title:'省内',
                    channelIds:122
                }
            ]
        },
        {
            title:'信用伦丛',
            channelIds:96,
            children:[
                {
                    title:'信用研究',
                    channelIds:123
                },
                {
                    title:'信用知识',
                    channelIds:124
                },
                {
                    title:'专家言论',
                    channelIds:125
                },
                {
                    title:'典型案例',
                    channelIds:126
                }
            ]
        },
    ]
}
